name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Download 32-bit artifacts
      - name: Download Windows Build Artifact (Default Features)
        uses: dawidd6/action-download-artifact@v9
        with:
          name: Windows Build (Default Features)
          workflow: rust.yml
          branch: current-bee
          path: ./artifacts/windows-default

      - name: Download Linux Build Artifact (Default Features)
        uses: dawidd6/action-download-artifact@v9
        with:
          name: Linux Build (Default Features)
          workflow: rust.yml
          branch: current-bee
          path: ./artifacts/linux-default

      # Download 64-bit artifacts
      - name: Download Windows x64 Build Artifact (Default Features)
        uses: dawidd6/action-download-artifact@v9
        with:
          name: Windows Build x64 (Default Features)
          workflow: rust.yml
          branch: current-bee
          path: ./artifacts/windows-x64-default

      - name: Download Linux x64 Build Artifact (Default Features)
        uses: dawidd6/action-download-artifact@v9
        with:
          name: Linux Build x64 (Default Features)
          workflow: rust.yml
          branch: current-bee
          path: ./artifacts/linux-x64-default

      # Download 32-bit artifacts (All Features)
      - name: Download Windows Build Artifact (All Features)
        uses: dawidd6/action-download-artifact@v9
        with:
          name: Windows Build (All Features)
          workflow: rust.yml
          branch: current-bee
          path: ./artifacts/windows-all

      - name: Download Linux Build Artifact (All Features)
        uses: dawidd6/action-download-artifact@v9
        with:
          name: Linux Build (All Features)
          workflow: rust.yml
          branch: current-bee
          path: ./artifacts/linux-all

      # Download 64-bit artifacts (All Features)
      - name: Download Windows x64 Build Artifact (All Features)
        uses: dawidd6/action-download-artifact@v9
        with:
          name: Windows Build x64 (All Features)
          workflow: rust.yml
          branch: current-bee
          path: ./artifacts/windows-x64-all

      - name: Download Linux x64 Build Artifact (All Features)
        uses: dawidd6/action-download-artifact@v9
        with:
          name: Linux Build x64 (All Features)
          workflow: rust.yml
          branch: current-bee
          path: ./artifacts/linux-x64-all

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: |
            ./artifacts/windows-all/i686-win7-windows-msvc/release/full_rust_g.dll
            ./artifacts/windows-all/i686-win7-windows-msvc/release/full_rust_g.pdb
            ./artifacts/linux-all/i686-unknown-linux-gnu/release/full_librust_g.so
            ./artifacts/windows-x64-all/x86_64-pc-windows-msvc/release/full_rust_g64.dll
            ./artifacts/windows-x64-all/x86_64-pc-windows-msvc/release/full_rust_g64.pdb
            ./artifacts/linux-x64-all/x86_64-unknown-linux-gnu/release/full_librust_g64.so
            ./artifacts/windows-all/full_rust_g.dm
            ./artifacts/windows-default/i686-win7-windows-msvc/release/rust_g.dll
            ./artifacts/windows-default/i686-win7-windows-msvc/release/rust_g.pdb
            ./artifacts/linux-default/i686-unknown-linux-gnu/release/librust_g.so
            ./artifacts/windows-x64-default/x86_64-pc-windows-msvc/release/rust_g64.dll
            ./artifacts/windows-x64-default/x86_64-pc-windows-msvc/release/rust_g64.pdb
            ./artifacts/linux-x64-default/x86_64-unknown-linux-gnu/release/librust_g64.so
            ./artifacts/windows-default/rust_g.dm
