name: rust-g
on: [push]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-pc-windows-msvc
      - uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: build
          args: --target i686-pc-windows-msvc --release
      - uses: actions/upload-artifact@v1
        with:
          name: rust_g.dll
          path: target/i686-pc-windows-msvc/release/rust_g.dll
  build-windows-full:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-pc-windows-msvc
      - uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: build
          args: --target i686-pc-windows-msvc --release --all-features
      - uses: actions/upload-artifact@v1
        with:
          name: full_rust_g.dll
          path: target/i686-pc-windows-msvc/release/rust_g.dll
  build-linux:
    runs-on: ubuntu-latest
    env:
      PKG_CONFIG_ALLOW_CROSS: 1
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install g++-multilib zlib1g-dev:i386 libssl-dev:i386 pkg-config:i386
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: build
          args: --target i686-unknown-linux-gnu --release
      - uses: actions/upload-artifact@v1
        with:
          name: librust_g.so
          path: target/i686-unknown-linux-gnu/release/librust_g.so
  build-linux-full:
    runs-on: ubuntu-latest
    env:
      PKG_CONFIG_ALLOW_CROSS: 1
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install g++-multilib zlib1g-dev:i386 libssl-dev:i386 pkg-config:i386
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: i686-unknown-linux-gnu
      - uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: build
          args: --target i686-unknown-linux-gnu --release --all-features
      - uses: actions/upload-artifact@v1
        with:
          name: full_librust_g.so
          path: target/i686-unknown-linux-gnu/release/librust_g.so
